### ISSUE TITLE
Does the "Download Images" page work?

### ISSUE THREAD

**Issue by RickCarlino** [joemcmanus/a01#1]
Hi Joe,

I've been following your project for a while. It's been a great reference point on how to use the camera APIs, perhaps even better than the official documentation in many ways.

Does the "Download Images" tab work on your machine? I tried it out a few weeks ago and could not get it to work. I was curious if it was still a work-in-progress or a configuration issue on my end.

Thanks!

**Comment by joemcmanus** [comment]
Hey Rick - Thanks for checking the app out! It does download the file, but it is not intuitive, which was an error on my part. It saves(downloads) the pics in to the directory images under flask. 

I sold my AIR so I can't test it right now. 

Cheers,
-Joe

**Comment by RickCarlino** [comment]
Thanks Joe - I will give it a look when I have access to the camera.

Not to get too off topic with this thread, but did you have any luck with the RTP/streaming APIs? I've followed the API docs, but get some not-so-descriptive errors. It seems like they're pretty focused on folks using the Android / iOS APIs.

**Comment by joemcmanus** [comment]
Oh yeah their whole focus is to write an app.I tinkered with RTP using tcpdump and then got frustrated. So yeah, I quit on that front. 

Cheers,
-Joe
